Project submission
umair-rao/Hello-World-FrontEnd pull request #1
Opened 2024-03-02 18:48 UTC by umair-rao

Instructions to run the project :
git checkout setup-react
npm install
npm start
This is Front-end of the application In which i have implemented the following things :

Create a new React app called 'hello-react-front-end'
Initialize your project with Git.
Create the App component with react-router.
Create the Greeting component that will display a greeting. Set it up as a route in your App component.
Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
Display the random greeting in your Greeting component.

2024-03-02 19:02 UTC, umair-rao commented
Please Approve my Project as the deadline is near. I have only this activity pending in my dashboard for the final Capstone Project Module.

2024-03-02 19:27 UTC, Efiamotu-1 requested changes
Hi @umair-rao, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-03-02 19:27 UTC, Efiamotu-1 commented on .babelrc
- [ ] Your project currently doesn't follow all of the project requirements for this milestone, please kindly work on it properly and make the necessary changes :+1: 
![prq](https://github.com/umair-rao/Hello-World-FrontEnd/assets/89055502/fdcb661d-516f-4b83-ba7f-adbb8b883deb)

2024-03-02 20:25 UTC, abdulhamiid requested changes
Hi @umair-rao 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ ❌ 

- Kindly add a customized readme in your backend repo and add a link to the frontend part.

- Please make sure that your project has a Postgres database set up.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-03-03 04:17 UTC, OyePriscilla requested changes
Hi @umair-rao 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Implement a connection between a Ruby on Rails back-end and React front-end. ✔️ 

## Required Changes ♻️

- [ ] Kindly ensure that the dependencies highlighted from the error message below are added and installed to your package.json. 🙏 

<img width="502" alt="Untitled" src="https://github.com/umair-rao/Hello-World-FrontEnd/assets/103386183/4436fd0d-c4a8-47ee-b3e1-27d2e0af16d3">

- [ ] Kindly don't disable any linters in `component/Greetings.js` file, I think you can address the issue that the linter is pointing at. 🙏 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-03-07 11:10 UTC, umair-rao commented
I have **already installed** the mentioned package (**You can verify** from paackage.json file) but the error still prisits therefore I have disabled linters for just this one line. I would Request the reviewer to please mention the solution before rejecting PR since I found the only way.
![Screenshot (5)](https://github.com/umair-rao/Hello-World-FrontEnd/assets/109624418/a54de1c9-0bc7-47bb-9eaa-59118426e067)

 
✅✅ **The project is working fine.** ✅✅

2024-03-07 11:22 UTC, OyePriscilla commented
Hi @umair-rao 👍, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that ought to be done in a fresh PR; kindly open a new PR and ensure that all the project milestones are done. 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-03-07 11:25 UTC, merged